language: python
sudo: required
python:
  - "3.5"
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database openctf;'
env:
  - SQLALCHEMY_DATABASE_URI=mysql://root:@localhost/openctf
script:
  - coverage run --source . -m pytest -v && coverage report
services:
  - mysql
notifications:
  email: false